leaguepedia:
  target: dev
  outputs:
    dev:
      type: postgres
      host: etl_db
      user: quocthanh
      password: "123"
      port: 5432
      dbname: ETL_Leaguepedia # or database instead of dbname
      schema: core
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
